# Generated by Django 3.0.4 on 2020-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='usr',
            field=models.CharField(default='mazek134', max_length=200),
        ),
    ]
