# Generated by Django 3.0.4 on 2020-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200409_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='usr',
            field=models.CharField(max_length=200),
        ),
    ]
